# Generated by Django 4.2 on 2026-03-08 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='total_games',
            field=models.IntegerField(default=10, help_text='Сколько игр будет сыграно в турнире', verbose_name='Количество игр'),
        ),
    ]
