# Generated by Django 4.2 on 2026-03-09 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_user_created_by_user_invitation_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='seating',
            field=models.JSONField(blank=True, default=dict, verbose_name='Рассадка'),
        ),
        migrations.AlterField(
            model_name='game',
            name='winning_team',
            field=models.CharField(blank=True, choices=[('mafia', 'Мафия'), ('peace', 'Мирные')], max_length=20, null=True),
        ),
    ]
