# Generated by Django 4.2 on 2026-03-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_game_seating_alter_game_winning_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.CharField(choices=[('BMF', 'БМФ'), ('KSL', 'КСЛ')], default='BMF', max_length=3, verbose_name='Правила турнира'),
        ),
    ]
