# Generated by Django 4.2 on 2026-03-09 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_tournament_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='lh_bonus',
            field=models.FloatField(default=0.0, verbose_name='Бонус за лучший ход'),
        ),
        migrations.AddField(
            model_name='playergamestats',
            name='yellow_cards',
            field=models.IntegerField(default=0, verbose_name='Жёлтые карточки'),
        ),
    ]
