# Generated by Django 4.2 on 2026-03-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0006_playergamestats_lh_bonus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='manual_penalty',
            field=models.FloatField(default=0.0, verbose_name='Ручной штраф'),
        ),
    ]
