# Generated by Django 4.2 on 2026-03-11 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0007_playergamestats_manual_penalty'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergamestats',
            name='yellow_penalty',
            field=models.FloatField(default=0.0, verbose_name='Штраф за ЖК'),
        ),
    ]
