# Generated by Django 4.2 on 2026-03-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_playergamestats_yellow_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergamestats',
            name='bonus_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Бонусные баллы'),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='ci',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ci коэффициент'),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='lh_bonus',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Бонус за лучший ход'),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='main_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Основные баллы'),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='manual_penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ручной штраф'),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='penalty_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Штрафные баллы'),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='total_score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='yellow_penalty',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Штраф за ЖК'),
        ),
    ]
