# Generated by Django 4.2 on 2026-03-17 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_alter_playergamestats_bonus_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='data_visible',
            field=models.BooleanField(default=True, verbose_name='Данные турнира видны всем'),
        ),
    ]
