# Generated by Django 4.2 on 2026-03-23 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0011_tournament_data_visible'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='completed_stats',
            field=models.JSONField(blank=True, default=dict, verbose_name='Статистика завершённого турнира'),
        ),
    ]
