# Generated by Django 4.2 on 2026-06-19 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0012_tournament_completed_at_tournament_completed_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Раздел правил',
                'verbose_name_plural': 'Разделы правил',
                'ordering': ['order'],
            },
        ),
        migrations.AlterField(
            model_name='playergamestats',
            name='penalty_score',
            field=models.FloatField(default=0.0, verbose_name='Штрафные баллы (ручной + ЖК)'),
        ),
        migrations.CreateModel(
            name='RuleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=20, verbose_name='Версия')),
                ('published_date', models.DateTimeField(verbose_name='Дата публикации')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активна')),
                ('changelog', models.TextField(blank=True, verbose_name='Что нового')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rule_versions', to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Версия правил',
                'verbose_name_plural': 'Версии правил',
                'ordering': ['-published_date'],
            },
        ),
        migrations.CreateModel(
            name='RuleSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='tournament.rulecategory', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Подраздел правил',
                'verbose_name_plural': 'Подразделы правил',
                'ordering': ['order'],
                'unique_together': {('category', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RuleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10, verbose_name='Номер')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tournament.rulesection', verbose_name='Подраздел')),
            ],
            options={
                'verbose_name': 'Пункт правил',
                'verbose_name_plural': 'Пункты правил',
                'ordering': ['order'],
                'unique_together': {('section', 'number')},
            },
        ),
        migrations.CreateModel(
            name='RuleHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст подсказки')),
                ('priority', models.IntegerField(choices=[(0, 'Низкий'), (1, 'Средний'), (2, 'Высокий')], default=0, verbose_name='Приоритет')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('rule_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hints', to='tournament.ruleitem', verbose_name='Пункт правил')),
            ],
            options={
                'verbose_name': 'Подсказка',
                'verbose_name_plural': 'Подсказки',
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='rulecategory',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournament.ruleversion', verbose_name='Версия'),
        ),
        migrations.CreateModel(
            name='RuleVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, verbose_name='Ключ')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('value', models.FloatField(verbose_name='Значение')),
                ('var_type', models.CharField(choices=[('penalty', 'Штраф'), ('bonus', 'Бонус'), ('coefficient', 'Коэффициент'), ('time', 'Время'), ('count', 'Количество')], default='penalty', max_length=20, verbose_name='Тип')),
                ('is_editable', models.BooleanField(default=True, verbose_name='Редактируемо')),
                ('rule_reference', models.CharField(blank=True, max_length=20, verbose_name='Ссылка на пункт правил')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='tournament.ruleversion', verbose_name='Версия')),
            ],
            options={
                'verbose_name': 'Переменная правил',
                'verbose_name_plural': 'Переменные правил',
                'ordering': ['key'],
                'unique_together': {('version', 'key')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='rulecategory',
            unique_together={('version', 'number')},
        ),
    ]
