# Generated by Django 4.2 on 2026-06-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0013_rulecategory_alter_playergamestats_penalty_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название тега')),
                ('color', models.CharField(default='#D4AF37', max_length=7, verbose_name='Цвет тега')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Тег правил',
                'verbose_name_plural': 'Теги правил',
                'ordering': ['name'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ruleitem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='ruleitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='direct_items', to='tournament.rulecategory', verbose_name='Раздел (прямые пункты)'),
        ),
        migrations.AlterField(
            model_name='ruleitem',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tournament.rulesection', verbose_name='Подраздел'),
        ),
        migrations.AddField(
            model_name='rulecategory',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rule_categories', to='tournament.ruletag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='ruleitem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rule_items', to='tournament.ruletag', verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='rulesection',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='rule_sections', to='tournament.ruletag', verbose_name='Теги'),
        ),
    ]
