# Generated by Django 4.2 on 2026-06-20 00:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0014_ruletag_alter_ruleitem_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rulecategory',
            name='changed_in_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_categories', to='tournament.ruleversion', verbose_name='Изменено в версии'),
        ),
        migrations.AddField(
            model_name='rulecategory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='rulecategory',
            name='is_changed',
            field=models.BooleanField(default=False, verbose_name='Изменено в этой версии'),
        ),
        migrations.AddField(
            model_name='rulecategory',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новое в этой версии'),
        ),
        migrations.AddField(
            model_name='rulecategory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='ruleitem',
            name='changed_in_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_items', to='tournament.ruleversion', verbose_name='Изменено в версии'),
        ),
        migrations.AddField(
            model_name='ruleitem',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='ruleitem',
            name='is_changed',
            field=models.BooleanField(default=False, verbose_name='Изменено в этой версии'),
        ),
        migrations.AddField(
            model_name='ruleitem',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новое в этой версии'),
        ),
        migrations.AddField(
            model_name='ruleitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
        migrations.AddField(
            model_name='rulesection',
            name='changed_in_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changed_sections', to='tournament.ruleversion', verbose_name='Изменено в версии'),
        ),
        migrations.AddField(
            model_name='rulesection',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Создано'),
        ),
        migrations.AddField(
            model_name='rulesection',
            name='is_changed',
            field=models.BooleanField(default=False, verbose_name='Изменено в этой версии'),
        ),
        migrations.AddField(
            model_name='rulesection',
            name='is_new',
            field=models.BooleanField(default=False, verbose_name='Новое в этой версии'),
        ),
        migrations.AddField(
            model_name='rulesection',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлено'),
        ),
    ]
