# Generated by Django 4.2 on 2026-06-20 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0015_rulecategory_changed_in_version_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RuleItemVariableLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placeholder', models.CharField(help_text='Текст в пункте, который будет заменён на значение переменной', max_length=100, verbose_name='Заполнитель')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variable_links', to='tournament.ruleitem', verbose_name='Пункт правил')),
                ('variable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_links', to='tournament.rulevariable', verbose_name='Переменная')),
            ],
            options={
                'verbose_name': 'Связь пункта с переменной',
                'verbose_name_plural': 'Связи пунктов с переменными',
                'ordering': ['order'],
                'unique_together': {('item', 'variable')},
            },
        ),
    ]
