# Generated by Django 4.2 on 2026-06-20 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0016_ruleitemvariablelink'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RuleItemVariableLink',
        ),
    ]
